### ISSUE TITLE
Find implicit jsx imports

### ISSUE THREAD

**Issue by MonsieurLanza** [PsychoLlama/further.vim#10]
Hello,

further.vim do not find `.jsx` files when not explicitely specified in path. E.g.
```js
import  { foo } from './bar';
``` 
where `./bar` refers to `./bar.jsx` will fail with `Can't find module "./bar".`

I did not find any config that would allow it, but I may have missed it.

**Comment by PsychoLlama** [comment]
@MonsieurLanza Hmmm, good point 🤔 
Under the hood I'm calling `require.resolve(...)`, so implicit extensions are limited to whatever node checks by default (AFAIK `.js`, `.json`, and `.node`).

As it stands, this is probably preventing further from being useful in projects using `.ts`, `.tsx`, `.jsx`, and `.mjs` extensions. All the codebases I work with use the `.js` extension so I guess I never really thought about it. Awkward 😳 

I've been meaning to replace the `require.resolve` step with a VimScript implementation anyway (better performance, cooler features). When I do, I'll make sure it supports those extensions out of the box. Thanks for letting me know!

**Comment by MonsieurLanza** [comment]
Thanks for your quick answer. I'll wait for an update. I have lived without it until now… :)

**Comment by PsychoLlama** [comment]
@MonsieurLanza good news! `.jsx` extensions are now supported :tada:

Let me know if it gives you any trouble 👍

**Comment by MonsieurLanza** [comment]
Yay !
